name: batgentic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=1.5.0
  - numpy>=1.21.0
  - librosa>=0.9.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - soundfile>=0.10.0
  - scipy>=1.9.0
  - pip
  - pip:
    - streamlit>=1.25.0
    - pyyaml>=6.0
    - python-dotenv>=0.19.0
    - plotly>=5.0.0